# """
# Django settings for firstproject project.

# Generated by 'django-admin startproject' using Django 5.0.3.

# For more information, see:
# https://docs.djangoproject.com/en/5.0/topics/settings/
# """

# from pathlib import Path
# import os
# import dj_database_url
# # -----------------------------
# # Base directory
# # -----------------------------
# BASE_DIR = Path(__file__).resolve().parent.parent

# # -----------------------------
# # Security
# # -----------------------------
# SECRET_KEY = 'django-insecure-xw&(plhzn(nammcrl@0e(!+%!o5$=^kk!n9yio_8%*h4-9w+)g'

# # Turn off debug mode in production
# DEBUG = False

# # Hosts allowed to serve your app
# ALLOWED_HOSTS = [
#     "127.0.0.1",
#     "localhost",
#     "firstproject-po3l.onrender.com",   # old one
#     "firstproject-1-f58i.onrender.com", # new one (your live URL)
# ]


# # -----------------------------
# # Installed applications
# # -----------------------------
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',

#     # Your apps
#     'service',
#     'theme',
#     'news',
#     'contactenquiry',

#     # Third-party apps
#     'tailwind',
#     'django_browser_reload',
#     'tinymce',
# ]

# # -----------------------------
# # Middleware
# # -----------------------------
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "whitenoise.middleware.WhiteNoiseMiddleware",  # For static files
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# # -----------------------------
# # Root URL configuration
# # -----------------------------
# ROOT_URLCONF = 'firstproject.urls'

# # -----------------------------
# # Templates
# # -----------------------------
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / "templates"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# # -----------------------------
# # WSGI
# # -----------------------------
# WSGI_APPLICATION = 'firstproject.wsgi.application'

# # Tailwind
# TAILWIND_APP_NAME = 'theme'

# # -----------------------------
# # Database
# # -----------------------------
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'firstprojectdb',
# #         'USER': 'myuser',        # PostgreSQL username
# #         'PASSWORD': 'postgres',# PostgreSQL password
# #         'HOST': 'localhost',           # Usually 'localhost'
# #         'PORT': '5432',   
# #     }
    
# # }


# DATABASES = {
#     "default": dj_database_url.config(
#         default="postgresql://myuser:postgres@localhost:5432/firstprojectdb"
#     )
# }

# # -----------------------------
# # Password validation
# # -----------------------------
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
# ]

# # -----------------------------
# # Internationalization
# # -----------------------------
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'Asia/Kathmandu'
# USE_I18N = True
# USE_TZ = True

# # -----------------------------
# # Static & media files
# # -----------------------------
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / "static"]
# STATIC_ROOT = BASE_DIR / "staticfiles"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# # Node path for Tailwind
# NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

# # -----------------------------
# # Default primary key
# # -----------------------------
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # -----------------------------
# # Email configuration
# # -----------------------------
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")



"""
Django settings for firstproject project.

Generated by 'django-admin startproject' using Django 5.0.3.
"""

from pathlib import Path
import os
import dj_database_url

# -----------------------------
# Base directory
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# Security
# -----------------------------
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-dev-secret-key"
)

# Turn off debug mode in production
DEBUG = os.environ.get("DEBUG", "False") == "True"

# Hosts allowed to serve your app
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "firstproject-1-f58i.onrender.com",
]

# -----------------------------
# Installed applications
# -----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'service',
    'theme',
    'news',
    'contactenquiry',

    # Third-party apps
    'tailwind',
    'django_browser_reload',
    'tinymce',
]

# -----------------------------
# Middleware
# -----------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # For static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------
# Root URL configuration
# -----------------------------
ROOT_URLCONF = 'firstproject.urls'

# -----------------------------
# Templates
# -----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -----------------------------
# WSGI
# -----------------------------
WSGI_APPLICATION = 'firstproject.wsgi.application'

# Tailwind
TAILWIND_APP_NAME = 'theme'

# -----------------------------
# Database
# -----------------------------
# Use DATABASE_URL from environment (Render), fallback to SQLite for dev
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False
    )
}

# -----------------------------
# Password validation
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -----------------------------
# Internationalization
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = True

# -----------------------------
# Static & media files
# -----------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------
# Node path for Tailwind
# -----------------------------
NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

# -----------------------------
# Default primary key
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------
# Email configuration
# -----------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
