# Generated by Django 5.2.3 on 2025-09-11 12:28

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('news_decs', tinymce.models.HTMLField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('news_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='news_title', unique=True)),
            ],
        ),
    ]
